
export { default as dze } from "./dze.jpg";
export { default as g20 } from "./g20.jpg";
export { default as lma } from "./lma.jpg";
export { default as bcra } from "./bcra.jpg";
export { default as exsa } from "./exsa.jpg";
export { default as disco } from "./disco.jpg";
export { default as mroyo } from "./mroyo.jpg";
export { default as hcank } from "./hcank.jpg";
export { default as jumbo } from "./jumbo.jpg";
export { default as moreno } from "./moreno.jpg";
export { default as posadas } from "./posadas.jpg";
export { default as polywall } from "./polywall.jpg";
export { default as ituzaingo } from "./ituzaingo.jpg";
export { default as monitoreo } from "./monitoreo.jpg";
export { default as alumbrado } from "./alumbrado.jpg";
export { default as provincia } from "./provincia.jpg";
export { default as globaltruck } from "./globaltruck.jpg";
export { default as asuntosInternos } from "./asuntos-internos.jpg";